import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";

const EGG_CATEGORY_LABELS = {
  big: "Big Eggs",
  jumbo: "Jumbo Eggs",
  turkey: "Turkey Eggs",
  normal: "Normal Eggs",
  small: "Small Eggs",
};

const getBase64Image = (img) => {
  const canvas = document.createElement("canvas");
  canvas.width = img.width;
  canvas.height = img.height;

  const ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0);

  return canvas.toDataURL("image/png");
};

export const generateInvoice = (sale) => {
  const doc = new jsPDF();

  const img = new Image();
  img.src = logo;

  img.onload = () => {
    const logoBase64 = getBase64Image(img);

    // ================= LOGO =================

    doc.addImage(logoBase64, "PNG", 14, 10, 24, 24);

    // ================= HEADER =================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(22, 101, 52);

    doc.text("MEBREK FARMS", 45, 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(80);

    doc.text("Poultry Farm Management System", 45, 25);
    doc.text("Egg Sales Invoice", 45, 31);

    doc.setDrawColor(22, 101, 52);
    doc.setLineWidth(0.5);
    doc.line(14, 40, 196, 40);

    // ================= CUSTOMER =================

    doc.setTextColor(0);
    doc.setFontSize(11);

    doc.text(`Customer: ${sale.customer || "-"}`, 14, 50);
    doc.text(
      `Date: ${sale.date ? new Date(sale.date).toLocaleDateString() : "-"}`,
      14,
      57,
    );

    // ================= CALCULATIONS =================
    // Sales now hold one line item per egg category instead of a single
    // flat crates/cratePrice/looseEggs/eggPrice set. Older sales saved
    // before this change won't have lineItems, so fall back to [].

    const lineItems = sale.lineItems || [];

    const transport = Number(sale.transportCharge || 0);
    const discount = Number(sale.discount || 0);

    const itemsTotal = lineItems.reduce(
      (sum, item) => sum + Number(item.subtotal || 0),
      0,
    );

    const grandTotal = sale.totalAmount ?? itemsTotal + transport - discount;

    // ================= TABLE =================
    // One row per egg category, then transport/discount as summary rows.

    const categoryRows = lineItems.map((item) => {
      const label = EGG_CATEGORY_LABELS[item.category] || item.category;
      const crates = Number(item.cratesSold || 0);
      const loose = Number(item.looseEggs || 0);
      const cratePrice = Number(item.cratePrice || 0);
      const eggPrice = Number(item.eggPrice || 0);

      const quantityLabel = [
        crates > 0 ? `${crates} crate${crates === 1 ? "" : "s"}` : null,
        loose > 0 ? `${loose} loose` : null,
      ]
        .filter(Boolean)
        .join(" + ");

      const unitPriceLabel = [
        crates > 0 ? `NGN ${cratePrice.toLocaleString()}/crate` : null,
        loose > 0 ? `NGN ${eggPrice.toLocaleString()}/egg` : null,
      ]
        .filter(Boolean)
        .join(", ");

      return [
        label,
        quantityLabel || "-",
        unitPriceLabel || "-",
        `NGN ${Number(item.subtotal || 0).toLocaleString()}`,
      ];
    });

    autoTable(doc, {
      startY: 68,
      head: [["Item", "Quantity", "Unit Price", "Amount"]],
      body: [
        ...(categoryRows.length
          ? categoryRows
          : [["No item details recorded", "", "", "NGN 0"]]),
        ["Transport", "", "", `NGN ${transport.toLocaleString()}`],
        ["Discount", "", "", `- NGN ${discount.toLocaleString()}`],
      ],
      theme: "grid",
      headStyles: {
        fillColor: [22, 101, 52],
        textColor: 255,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 10,
        cellPadding: 4,
      },
    });

    let y = doc.lastAutoTable.finalY + 15;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);

    doc.text(`Grand Total: NGN ${Number(grandTotal).toLocaleString()}`, 125, y);

    y += 8;
    doc.text(
      `Amount Paid: NGN ${Number(sale.amountPaid || 0).toLocaleString()}`,
      125,
      y,
    );

    y += 8;
    doc.text(
      `Balance: NGN ${Number(sale.balance || 0).toLocaleString()}`,
      125,
      y,
    );

    y += 8;
    doc.text(`Status: ${sale.status || "UNPAID"}`, 125, y);

    // ================= FOOTER =================

    y += 25;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);

    doc.text("Thank you for choosing Mebrek Farms.", 14, y);
    doc.text("Generated by Mebrek Farm Management System", 14, y + 7);

    // ================= SAVE =================

    doc.save(`Invoice-${sale.customer || "Customer"}.pdf`);
  };

  img.onerror = () => {
    console.error("Failed to load logo.");
  };
};
