import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";

const getBase64Image = (img) => {
  const canvas = document.createElement("canvas");
  canvas.width = img.width;
  canvas.height = img.height;

  const ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0);

  return canvas.toDataURL("image/png");
};

export const generateInvoice = (sale) => {
  const doc = new jsPDF();

  const img = new Image();
  img.src = logo;

  img.onload = () => {
    const logoBase64 = getBase64Image(img);

    // ================= LOGO =================

    doc.addImage(logoBase64, "PNG", 14, 10, 24, 24);

    // ================= HEADER =================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(22, 101, 52);

    doc.text("MEBREK FARMS", 45, 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(80);

    doc.text("Poultry Farm Management System", 45, 25);
    doc.text("Egg Sales Invoice", 45, 31);

    doc.setDrawColor(22, 101, 52);
    doc.setLineWidth(0.5);
    doc.line(14, 40, 196, 40);

    // ================= CUSTOMER =================

    doc.setTextColor(0);
    doc.setFontSize(11);

    doc.text(`Customer: ${sale.customer || "-"}`, 14, 50);
    doc.text(
      `Date: ${sale.date ? new Date(sale.date).toLocaleDateString() : "-"}`,
      14,
      57,
    );

    // ================= CALCULATIONS =================

    const crates = Number(sale.cratesSold || 0);
    const cratePrice = Number(sale.cratePrice || 0);

    const loose = Number(sale.looseEggs || 0);
    const eggPrice = Number(sale.eggPrice || 0);

    const transport = Number(sale.transportCharge || 0);
    const discount = Number(sale.discount || 0);

    const crateTotal = crates * cratePrice;
    const looseTotal = loose * eggPrice;

    const grandTotal =
      sale.totalAmount ?? crateTotal + looseTotal + transport - discount;

    // ================= TABLE =================

    autoTable(doc, {
      startY: 68,
      head: [["Item", "Quantity", "Unit Price", "Amount"]],
      body: [
        [
          "Egg Crates",
          crates,
          `₦${cratePrice.toLocaleString()}`,
          `₦${crateTotal.toLocaleString()}`,
        ],
        [
          "Loose Eggs",
          loose,
          `₦${eggPrice.toLocaleString()}`,
          `₦${looseTotal.toLocaleString()}`,
        ],
        ["Transport", "", "", `₦${transport.toLocaleString()}`],
        ["Discount", "", "", `- ₦${discount.toLocaleString()}`],
      ],
      theme: "grid",
      headStyles: {
        fillColor: [22, 101, 52],
        textColor: 255,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 10,
        cellPadding: 4,
      },
    });

    let y = doc.lastAutoTable.finalY + 15;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);

    doc.text(`Grand Total: ₦${Number(grandTotal).toLocaleString()}`, 125, y);

    y += 8;
    doc.text(
      `Amount Paid: ₦${Number(sale.amountPaid || 0).toLocaleString()}`,
      125,
      y,
    );

    y += 8;
    doc.text(`Balance: ₦${Number(sale.balance || 0).toLocaleString()}`, 125, y);

    y += 8;
    doc.text(`Status: ${sale.status || "UNPAID"}`, 125, y);

    // ================= FOOTER =================

    y += 25;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);

    doc.text("Thank you for choosing Mebrek Farms.", 14, y);
    doc.text("Generated by Mebrek Farm Management System", 14, y + 7);

    // ================= SAVE =================

    doc.save(`Invoice-${sale.customer || "Customer"}.pdf`);
  };

  img.onerror = () => {
    console.error("Failed to load logo.");
  };
};
