import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";

// jsPDF's built-in Helvetica font can't render the ₦ glyph — it draws
// garbled characters in its place. Using "NGN" here from the start,
// rather than the Naira symbol, avoids that bug entirely (same fix
// applied to the egg sales invoice generator after it shipped with
// the symbol and broke).
const MANURE_CATEGORY_LABELS = {
  dry: "Dry Manure",
  wet: "Wet Manure",
};

const getBase64Image = (img) => {
  const canvas = document.createElement("canvas");
  canvas.width = img.width;
  canvas.height = img.height;

  const ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0);

  return canvas.toDataURL("image/png");
};

export const generateManureInvoice = (sale) => {
  const doc = new jsPDF();

  const img = new Image();
  img.src = logo;

  img.onload = () => {
    const logoBase64 = getBase64Image(img);

    // ================= LOGO =================

    doc.addImage(logoBase64, "PNG", 14, 10, 24, 24);

    // ================= HEADER =================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(146, 64, 14);

    doc.text("MEBREK FARMS", 45, 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(80);

    doc.text("Poultry Farm Management System", 45, 25);
    doc.text("Manure Sales Invoice", 45, 31);

    doc.setDrawColor(146, 64, 14);
    doc.setLineWidth(0.5);
    doc.line(14, 40, 196, 40);

    // ================= CUSTOMER =================

    doc.setTextColor(0);
    doc.setFontSize(11);

    doc.text(`Customer: ${sale.customer || "-"}`, 14, 50);
    doc.text(
      `Date: ${sale.date ? new Date(sale.date).toLocaleDateString() : "-"}`,
      14,
      57,
    );
    doc.text(`Invoice #: ${sale.invoiceNumber || "-"}`, 14, 64);

    // ================= CALCULATIONS =================
    // One line item per manure category (dry/wet), each already
    // carrying its own validated pricePerBag and subtotal from the
    // backend — nothing recalculated here, just formatted for print.

    const lineItems = sale.lineItems || [];

    const transport = Number(sale.transportCharge || 0);
    const discount = Number(sale.discount || 0);

    const itemsTotal = lineItems.reduce(
      (sum, item) => sum + Number(item.subtotal || 0),
      0,
    );

    const grandTotal = sale.totalAmount ?? itemsTotal + transport - discount;

    // ================= TABLE =================

    const categoryRows = lineItems.map((item) => {
      const label = MANURE_CATEGORY_LABELS[item.category] || item.category;
      const bags = Number(item.bags || 0);
      const pricePerBag = Number(item.pricePerBag || 0);

      return [
        label,
        `${bags} bag${bags === 1 ? "" : "s"}`,
        `NGN ${pricePerBag.toLocaleString()}/bag`,
        `NGN ${Number(item.subtotal || 0).toLocaleString()}`,
      ];
    });

    autoTable(doc, {
      startY: 72,
      head: [["Item", "Quantity", "Unit Price", "Amount"]],
      body: [
        ...(categoryRows.length
          ? categoryRows
          : [["No item details recorded", "", "", "NGN 0"]]),
        ["Transport", "", "", `NGN ${transport.toLocaleString()}`],
        ["Discount", "", "", `- NGN ${discount.toLocaleString()}`],
      ],
      theme: "grid",
      headStyles: {
        fillColor: [146, 64, 14],
        textColor: 255,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 10,
        cellPadding: 4,
      },
    });

    let y = doc.lastAutoTable.finalY + 15;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);

    doc.text(`Grand Total: NGN ${Number(grandTotal).toLocaleString()}`, 125, y);

    y += 8;
    doc.text(
      `Amount Paid: NGN ${Number(sale.amountPaid || 0).toLocaleString()}`,
      125,
      y,
    );

    y += 8;
    doc.text(
      `Balance: NGN ${Number(sale.balance || 0).toLocaleString()}`,
      125,
      y,
    );

    y += 8;
    doc.text(`Status: ${sale.status || "UNPAID"}`, 125, y);

    // ================= FOOTER =================

    y += 25;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);

    doc.text("Thank you for choosing Mebrek Farms.", 14, y);
    doc.text("Generated by Mebrek Farm Management System", 14, y + 7);

    // ================= SAVE =================

    doc.save(`Manure-Invoice-${sale.customer || "Customer"}.pdf`);
  };

  img.onerror = () => {
    console.error("Failed to load logo.");
  };
};
