const mongoose = require("mongoose");

// Assumption: your spec didn't list specific Category options, so I've
// picked a reasonable common set for poultry health. Let me know if you
// want different/additional categories.
const CATEGORIES = [
  "Respiratory",
  "Digestive",
  "Parasitic",
  "Bacterial",
  "Viral",
  "Nutritional Deficiency",
  "Injury",
  "Other",
  // Auto-generated by cross-module hooks (Vaccination/Medication/Mortality
  // creation) so those modules don't need duplicate manual entry here.
  "Vaccination",
  "Medication",
  "Mortality",
];

const birdHealthSchema = new mongoose.Schema(
  {
    // ================= EXISTING FIELDS (unchanged) =================
    date: {
      type: Date,
      required: [true, "Date is required"],
      default: Date.now,
    },
    pen: {
      type: String,
      required: true,
      enum: [
        "Battery Cage Row 1",
        "Battery Cage Row 2",
        "Battery Cage Row 3",
        "Deep Litter Pen 1",
        "Deep Litter Pen 2",
        "Deep Litter Pen 3",
        "Deep Litter Pen 4",
        "Deep Litter Pen 5",
        "Sick Bay",
        "Pen 150",
      ],
    },
    healthIssue: {
      type: String,
      required: [true, "Health issue / disease is required"],
      trim: true,
    },
    birdsAffected: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    symptoms: {
      type: String,
      trim: true,
      default: "",
    },
    severity: {
      type: String,
      enum: ["Low", "Medium", "High", "Critical"],
      default: "Low",
    },
    vetConsulted: {
      type: Boolean,
      default: false,
    },
    diagnosis: {
      type: String,
      trim: true,
      default: "",
    },
    // Treated as the schema's home for the new spec's "Treatment Given"
    // field — no rename, to avoid touching existing data.
    actionTaken: {
      type: String,
      trim: true,
      default: "",
    },
    // Superset of the old and new spec's status values, per your choice:
    // "Under Treatment"/"Dead" are the original values; "Active"/"Recovering"
    // are the new spec's values. Both sets stay valid going forward.
    status: {
      type: String,
      enum: [
        "Under Treatment",
        "Active",
        "Recovering",
        "Recovered",
        "Isolated",
        "Dead",
      ],
      default: "Under Treatment",
    },
    remarks: {
      type: String,
      trim: true,
      default: "",
    },

    recordedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
    },

    isDeleted: {
      type: Boolean,
      default: false,
    },
    deletedAt: {
      type: Date,
      default: null,
    },
    deletedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
      default: null,
    },

    // ================= NEW FIELDS (Phase 1 additions) =================
    category: {
      type: String,
      enum: CATEGORIES,
    },

    medicationUsed: {
      type: String,
      trim: true,
    },

    // Distinct from the existing vetConsulted boolean — this is the
    // actual name of the vet/person who attended, not just a yes/no flag.
    veterinarianName: {
      type: String,
      trim: true,
    },

    followUpDate: {
      type: Date,
      default: null,
    },

    // Recalculated by the pre-save hook below whenever the record is
    // saved, and also recomputed live on every read by the controller
    // (same belt-and-suspenders approach as the Vaccination model), so
    // it stays accurate day-to-day even between saves.
    followUpStatus: {
      type: String,
      enum: ["Upcoming", "Due Today", "Overdue", "Completed"],
      default: "Completed",
    },
    costOfTreatment: {
      type: Number,
      default: 0,
      min: [0, "costOfTreatment cannot be negative"],
    },

    currency: {
      type: String,
      default: "NGN",
    },

    recoveryDate: {
      type: Date,
      default: null,
    },

    mortalityRecord: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Mortality",
      default: null,
    },

    medicationRecord: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Medication",
      default: null,
    },
    // Denormalized alongside the existing deletedBy ObjectId ref, matching
    // the pattern used in Feed/Vaccinations, so the frontend can show
    // "Deleted by X (role)" without waiting on a populate() call.
    deletedByName: {
      type: String,
      default: null,
    },
    deletedByRole: {
      type: String,
      default: null,
    },
  },
  { timestamps: true },
);

// Recalculate followUpStatus based on followUpDate whenever the record
// is saved. Written async/no-next (the modern Mongoose middleware form)
// to avoid the callback-detection quirk that caused a crash on the
// Vaccination model's equivalent hook.
birdHealthSchema.pre("save", async function () {
  if (!this.followUpDate) {
    this.followUpStatus = "Completed";
    return;
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const due = new Date(this.followUpDate);
  due.setHours(0, 0, 0, 0);

  if (due.getTime() < today.getTime()) {
    this.followUpStatus = "Overdue";
  } else if (due.getTime() === today.getTime()) {
    this.followUpStatus = "Due Today";
  } else {
    this.followUpStatus = "Upcoming";
  }
});

birdHealthSchema.index({ isDeleted: 1, date: -1 });
birdHealthSchema.index({ followUpDate: 1 });
birdHealthSchema.index({ status: 1 });
birdHealthSchema.index({ severity: 1 });

birdHealthSchema.index({
  pen: "text",
  healthIssue: "text",
  diagnosis: "text",
  medicationUsed: "text",
  veterinarianName: "text",
});

birdHealthSchema.statics.CATEGORIES = CATEGORIES;

module.exports = mongoose.model("BirdHealth", birdHealthSchema);
